---
stages:
  - renovate

variables:
  RENOVATE_BASE_DIR: $CI_PROJECT_DIR/renovate
  RENOVATE_ENDPOINT: $CI_API_V4_URL
  RENOVATE_PLATFORM: gitlab
  RENOVATE_REQUIRE_CONFIG: 'true'
  RENOVATE_ONBOARDING: "false"
  LOG_LEVEL: debug
  RENOVATE_AUTODISCOVER: 'true'
  RENOVATE_PRINT_CONFIG: 'true'
  RENOVATE_PR_CREATION: 'immediate'
  RENOVATE_PR_HOURLY_LIMIT: 1
  RENOVATE_PR_CONCURRENT_LIMIT: 2

renovate:
  stage: renovate
  resource_group: production
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/renovate/renovate:32.11.3
  timeout: 2h
  variables:
    KUBERNETES_MEMORY_REQUEST: 2Gi
    KUBERNETES_MEMORY_LIMIT: 3Gi
    KUBERNETES_CPU_REQUEST: 1000m
    KUBERNETES_CPU_LIMIT: 1000m
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  script:
    - renovate $RENOVATE_EXTRA_FLAGS
